window.KX_DATA = {
  "meta": {
    "gameTitle": "快闪图形",
    "sourceLevelFields": [
      "ID",
      "Level",
      "Rate",
      "Type",
      "MissionNum",
      "MissionPass",
      "Fault",
      "Time",
      "Brains",
      "Score",
      "Scores",
      "Reward",
      "RewardNum",
      "Limit"
    ],
    "sourceShapeFields": [
      "记录号",
      "ID",
      "Color",
      "Shape",
      "Texture",
      "Icon"
    ],
    "targetCountRule": "运行时优先读取每关 TargetCount；若旧表无 TargetCount/TargetNum，才回退为 ceil(Scores / Score)。本包已为 50 关补齐 TargetCount。",
    "scoreRule": "通关：round(PassScore或Scores + (实际数 - TargetCount) * RewardScore或Score + 10)；未通关：固定 10。",
    "endRule": "小关在连续选错两次、本关倒计时为0或总训练时间到0时结算；训练总时间到0后结束训练并传出通关标识。",
    "difficultyRule": "通关难度+1；连续失败序列中，第1次原难度，第2次相对序列起始等级-1，第3次相对序列起始等级-3并清空失败计数；最低1级。",
    "shapeTypeRanges": {
      "1": [
        1,
        30
      ],
      "2": [
        31,
        62
      ],
      "3": [
        63,
        100
      ]
    },
    "assetVersion": "refined-polished-difficulty-2026-05-13",
    "assetPolicy": "原始矢量素材，SVG + PNG 双格式；用于离线 HTML5 游戏。",
    "resultEmitRule": "训练结束时传出 KX_TRAINING_END：调用 window.KX_onTrainingEnd(payload)，派发 CustomEvent，向父页面 postMessage，并写入 localStorage.KX_LAST_TRAINING_RESULT。",
    "iconRule": "渲染优先读取图形表 Icon 字段，并加载 assets/icons/{Icon}.svg；无 Icon 时回退 assets/shapes/shape_###.svg。",
    "shapeRangeRule": "每关优先读取 ShapeRange/ShapeMin+ShapeMax/RangeStart+RangeEnd；无关卡级范围时回退 Type 对应的 shapeRanges。",
    "difficultyPresets": [
      {
        "id": "easy",
        "label": "容易",
        "startLevel": 1,
        "description": "从第1关开始"
      },
      {
        "id": "normal",
        "label": "普通",
        "startLevel": 15,
        "description": "从第15关开始"
      },
      {
        "id": "hard",
        "label": "困难",
        "startLevel": 30,
        "description": "从第30关开始"
      }
    ],
    "difficultyPresetRule": "菜单只提供容易、普通、困难三个起始难度；分别固定从第1、15、30关开始，训练中仍按通关/失败规则动态升降关。"
  },
  "colors": {
    "1": {
      "name": "蓝",
      "hex": "#3F82FF"
    },
    "2": {
      "name": "灰",
      "hex": "#9AA3B2"
    },
    "3": {
      "name": "绿",
      "hex": "#45D28B"
    },
    "4": {
      "name": "橙",
      "hex": "#FF9A2E"
    },
    "5": {
      "name": "粉",
      "hex": "#FF72B6"
    },
    "6": {
      "name": "紫",
      "hex": "#9A68FF"
    },
    "7": {
      "name": "红",
      "hex": "#FF4D5E"
    },
    "8": {
      "name": "黄",
      "hex": "#FFD64D"
    }
  },
  "shapeNames": {
    "1": "五边形",
    "2": "铜钱形",
    "3": "五角星",
    "4": "十字架",
    "5": "三角形"
  },
  "textureNames": {
    "1": "空",
    "2": "正方纹",
    "3": "斜条纹"
  },
  "shapeRanges": {
    "1": [
      1,
      30
    ],
    "2": [
      31,
      62
    ],
    "3": [
      63,
      100
    ]
  },
  "shapes": [
    {
      "Floor": 1,
      "ID": 1,
      "Color": 1,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon1",
      "IconSvg": "assets/icons/Icon1.svg",
      "IconPng": "assets/icons_png/Icon1.png"
    },
    {
      "Floor": 2,
      "ID": 2,
      "Color": 1,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon2",
      "IconSvg": "assets/icons/Icon2.svg",
      "IconPng": "assets/icons_png/Icon2.png"
    },
    {
      "Floor": 3,
      "ID": 3,
      "Color": 1,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon3",
      "IconSvg": "assets/icons/Icon3.svg",
      "IconPng": "assets/icons_png/Icon3.png"
    },
    {
      "Floor": 4,
      "ID": 4,
      "Color": 1,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon4",
      "IconSvg": "assets/icons/Icon4.svg",
      "IconPng": "assets/icons_png/Icon4.png"
    },
    {
      "Floor": 5,
      "ID": 5,
      "Color": 1,
      "Shape": 5,
      "Texture": 1,
      "Icon": "Icon5",
      "IconSvg": "assets/icons/Icon5.svg",
      "IconPng": "assets/icons_png/Icon5.png"
    },
    {
      "Floor": 6,
      "ID": 6,
      "Color": 1,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon6",
      "IconSvg": "assets/icons/Icon6.svg",
      "IconPng": "assets/icons_png/Icon6.png"
    },
    {
      "Floor": 7,
      "ID": 7,
      "Color": 1,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon7",
      "IconSvg": "assets/icons/Icon7.svg",
      "IconPng": "assets/icons_png/Icon7.png"
    },
    {
      "Floor": 8,
      "ID": 8,
      "Color": 1,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon8",
      "IconSvg": "assets/icons/Icon8.svg",
      "IconPng": "assets/icons_png/Icon8.png"
    },
    {
      "Floor": 9,
      "ID": 9,
      "Color": 1,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon9",
      "IconSvg": "assets/icons/Icon9.svg",
      "IconPng": "assets/icons_png/Icon9.png"
    },
    {
      "Floor": 10,
      "ID": 10,
      "Color": 1,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon10",
      "IconSvg": "assets/icons/Icon10.svg",
      "IconPng": "assets/icons_png/Icon10.png"
    },
    {
      "Floor": 11,
      "ID": 11,
      "Color": 1,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon11",
      "IconSvg": "assets/icons/Icon11.svg",
      "IconPng": "assets/icons_png/Icon11.png"
    },
    {
      "Floor": 12,
      "ID": 12,
      "Color": 1,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon12",
      "IconSvg": "assets/icons/Icon12.svg",
      "IconPng": "assets/icons_png/Icon12.png"
    },
    {
      "Floor": 13,
      "ID": 13,
      "Color": 1,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon13",
      "IconSvg": "assets/icons/Icon13.svg",
      "IconPng": "assets/icons_png/Icon13.png"
    },
    {
      "Floor": 14,
      "ID": 14,
      "Color": 2,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon14",
      "IconSvg": "assets/icons/Icon14.svg",
      "IconPng": "assets/icons_png/Icon14.png"
    },
    {
      "Floor": 15,
      "ID": 15,
      "Color": 2,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon15",
      "IconSvg": "assets/icons/Icon15.svg",
      "IconPng": "assets/icons_png/Icon15.png"
    },
    {
      "Floor": 16,
      "ID": 16,
      "Color": 2,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon16",
      "IconSvg": "assets/icons/Icon16.svg",
      "IconPng": "assets/icons_png/Icon16.png"
    },
    {
      "Floor": 17,
      "ID": 17,
      "Color": 2,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon17",
      "IconSvg": "assets/icons/Icon17.svg",
      "IconPng": "assets/icons_png/Icon17.png"
    },
    {
      "Floor": 18,
      "ID": 18,
      "Color": 2,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon18",
      "IconSvg": "assets/icons/Icon18.svg",
      "IconPng": "assets/icons_png/Icon18.png"
    },
    {
      "Floor": 19,
      "ID": 19,
      "Color": 2,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon19",
      "IconSvg": "assets/icons/Icon19.svg",
      "IconPng": "assets/icons_png/Icon19.png"
    },
    {
      "Floor": 20,
      "ID": 20,
      "Color": 2,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon20",
      "IconSvg": "assets/icons/Icon20.svg",
      "IconPng": "assets/icons_png/Icon20.png"
    },
    {
      "Floor": 21,
      "ID": 21,
      "Color": 2,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon21",
      "IconSvg": "assets/icons/Icon21.svg",
      "IconPng": "assets/icons_png/Icon21.png"
    },
    {
      "Floor": 22,
      "ID": 22,
      "Color": 2,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon22",
      "IconSvg": "assets/icons/Icon22.svg",
      "IconPng": "assets/icons_png/Icon22.png"
    },
    {
      "Floor": 23,
      "ID": 23,
      "Color": 2,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon23",
      "IconSvg": "assets/icons/Icon23.svg",
      "IconPng": "assets/icons_png/Icon23.png"
    },
    {
      "Floor": 24,
      "ID": 24,
      "Color": 2,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon24",
      "IconSvg": "assets/icons/Icon24.svg",
      "IconPng": "assets/icons_png/Icon24.png"
    },
    {
      "Floor": 25,
      "ID": 25,
      "Color": 2,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon25",
      "IconSvg": "assets/icons/Icon25.svg",
      "IconPng": "assets/icons_png/Icon25.png"
    },
    {
      "Floor": 26,
      "ID": 26,
      "Color": 3,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon26",
      "IconSvg": "assets/icons/Icon26.svg",
      "IconPng": "assets/icons_png/Icon26.png"
    },
    {
      "Floor": 27,
      "ID": 27,
      "Color": 3,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon27",
      "IconSvg": "assets/icons/Icon27.svg",
      "IconPng": "assets/icons_png/Icon27.png"
    },
    {
      "Floor": 28,
      "ID": 28,
      "Color": 3,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon28",
      "IconSvg": "assets/icons/Icon28.svg",
      "IconPng": "assets/icons_png/Icon28.png"
    },
    {
      "Floor": 29,
      "ID": 29,
      "Color": 3,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon29",
      "IconSvg": "assets/icons/Icon29.svg",
      "IconPng": "assets/icons_png/Icon29.png"
    },
    {
      "Floor": 30,
      "ID": 30,
      "Color": 3,
      "Shape": 5,
      "Texture": 1,
      "Icon": "Icon30",
      "IconSvg": "assets/icons/Icon30.svg",
      "IconPng": "assets/icons_png/Icon30.png"
    },
    {
      "Floor": 31,
      "ID": 31,
      "Color": 3,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon31",
      "IconSvg": "assets/icons/Icon31.svg",
      "IconPng": "assets/icons_png/Icon31.png"
    },
    {
      "Floor": 32,
      "ID": 32,
      "Color": 3,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon32",
      "IconSvg": "assets/icons/Icon32.svg",
      "IconPng": "assets/icons_png/Icon32.png"
    },
    {
      "Floor": 33,
      "ID": 33,
      "Color": 3,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon33",
      "IconSvg": "assets/icons/Icon33.svg",
      "IconPng": "assets/icons_png/Icon33.png"
    },
    {
      "Floor": 34,
      "ID": 34,
      "Color": 3,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon34",
      "IconSvg": "assets/icons/Icon34.svg",
      "IconPng": "assets/icons_png/Icon34.png"
    },
    {
      "Floor": 35,
      "ID": 35,
      "Color": 3,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon35",
      "IconSvg": "assets/icons/Icon35.svg",
      "IconPng": "assets/icons_png/Icon35.png"
    },
    {
      "Floor": 36,
      "ID": 36,
      "Color": 3,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon36",
      "IconSvg": "assets/icons/Icon36.svg",
      "IconPng": "assets/icons_png/Icon36.png"
    },
    {
      "Floor": 37,
      "ID": 37,
      "Color": 3,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon37",
      "IconSvg": "assets/icons/Icon37.svg",
      "IconPng": "assets/icons_png/Icon37.png"
    },
    {
      "Floor": 38,
      "ID": 38,
      "Color": 3,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon38",
      "IconSvg": "assets/icons/Icon38.svg",
      "IconPng": "assets/icons_png/Icon38.png"
    },
    {
      "Floor": 39,
      "ID": 39,
      "Color": 4,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon39",
      "IconSvg": "assets/icons/Icon39.svg",
      "IconPng": "assets/icons_png/Icon39.png"
    },
    {
      "Floor": 40,
      "ID": 40,
      "Color": 4,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon40",
      "IconSvg": "assets/icons/Icon40.svg",
      "IconPng": "assets/icons_png/Icon40.png"
    },
    {
      "Floor": 41,
      "ID": 41,
      "Color": 4,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon41",
      "IconSvg": "assets/icons/Icon41.svg",
      "IconPng": "assets/icons_png/Icon41.png"
    },
    {
      "Floor": 42,
      "ID": 42,
      "Color": 4,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon42",
      "IconSvg": "assets/icons/Icon42.svg",
      "IconPng": "assets/icons_png/Icon42.png"
    },
    {
      "Floor": 43,
      "ID": 43,
      "Color": 4,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon43",
      "IconSvg": "assets/icons/Icon43.svg",
      "IconPng": "assets/icons_png/Icon43.png"
    },
    {
      "Floor": 44,
      "ID": 44,
      "Color": 4,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon44",
      "IconSvg": "assets/icons/Icon44.svg",
      "IconPng": "assets/icons_png/Icon44.png"
    },
    {
      "Floor": 45,
      "ID": 45,
      "Color": 4,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon45",
      "IconSvg": "assets/icons/Icon45.svg",
      "IconPng": "assets/icons_png/Icon45.png"
    },
    {
      "Floor": 46,
      "ID": 46,
      "Color": 4,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon46",
      "IconSvg": "assets/icons/Icon46.svg",
      "IconPng": "assets/icons_png/Icon46.png"
    },
    {
      "Floor": 47,
      "ID": 47,
      "Color": 4,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon47",
      "IconSvg": "assets/icons/Icon47.svg",
      "IconPng": "assets/icons_png/Icon47.png"
    },
    {
      "Floor": 48,
      "ID": 48,
      "Color": 4,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon48",
      "IconSvg": "assets/icons/Icon48.svg",
      "IconPng": "assets/icons_png/Icon48.png"
    },
    {
      "Floor": 49,
      "ID": 49,
      "Color": 4,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon49",
      "IconSvg": "assets/icons/Icon49.svg",
      "IconPng": "assets/icons_png/Icon49.png"
    },
    {
      "Floor": 50,
      "ID": 50,
      "Color": 4,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon50",
      "IconSvg": "assets/icons/Icon50.svg",
      "IconPng": "assets/icons_png/Icon50.png"
    },
    {
      "Floor": 51,
      "ID": 51,
      "Color": 5,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon51",
      "IconSvg": "assets/icons/Icon51.svg",
      "IconPng": "assets/icons_png/Icon51.png"
    },
    {
      "Floor": 52,
      "ID": 52,
      "Color": 5,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon52",
      "IconSvg": "assets/icons/Icon52.svg",
      "IconPng": "assets/icons_png/Icon52.png"
    },
    {
      "Floor": 53,
      "ID": 53,
      "Color": 5,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon53",
      "IconSvg": "assets/icons/Icon53.svg",
      "IconPng": "assets/icons_png/Icon53.png"
    },
    {
      "Floor": 54,
      "ID": 54,
      "Color": 5,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon54",
      "IconSvg": "assets/icons/Icon54.svg",
      "IconPng": "assets/icons_png/Icon54.png"
    },
    {
      "Floor": 55,
      "ID": 55,
      "Color": 5,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon55",
      "IconSvg": "assets/icons/Icon55.svg",
      "IconPng": "assets/icons_png/Icon55.png"
    },
    {
      "Floor": 56,
      "ID": 56,
      "Color": 5,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon56",
      "IconSvg": "assets/icons/Icon56.svg",
      "IconPng": "assets/icons_png/Icon56.png"
    },
    {
      "Floor": 57,
      "ID": 57,
      "Color": 5,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon57",
      "IconSvg": "assets/icons/Icon57.svg",
      "IconPng": "assets/icons_png/Icon57.png"
    },
    {
      "Floor": 58,
      "ID": 58,
      "Color": 5,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon58",
      "IconSvg": "assets/icons/Icon58.svg",
      "IconPng": "assets/icons_png/Icon58.png"
    },
    {
      "Floor": 59,
      "ID": 59,
      "Color": 5,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon59",
      "IconSvg": "assets/icons/Icon59.svg",
      "IconPng": "assets/icons_png/Icon59.png"
    },
    {
      "Floor": 60,
      "ID": 60,
      "Color": 5,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon60",
      "IconSvg": "assets/icons/Icon60.svg",
      "IconPng": "assets/icons_png/Icon60.png"
    },
    {
      "Floor": 61,
      "ID": 61,
      "Color": 5,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon61",
      "IconSvg": "assets/icons/Icon61.svg",
      "IconPng": "assets/icons_png/Icon61.png"
    },
    {
      "Floor": 62,
      "ID": 62,
      "Color": 5,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon62",
      "IconSvg": "assets/icons/Icon62.svg",
      "IconPng": "assets/icons_png/Icon62.png"
    },
    {
      "Floor": 63,
      "ID": 63,
      "Color": 6,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon63",
      "IconSvg": "assets/icons/Icon63.svg",
      "IconPng": "assets/icons_png/Icon63.png"
    },
    {
      "Floor": 64,
      "ID": 64,
      "Color": 6,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon64",
      "IconSvg": "assets/icons/Icon64.svg",
      "IconPng": "assets/icons_png/Icon64.png"
    },
    {
      "Floor": 65,
      "ID": 65,
      "Color": 6,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon65",
      "IconSvg": "assets/icons/Icon65.svg",
      "IconPng": "assets/icons_png/Icon65.png"
    },
    {
      "Floor": 66,
      "ID": 66,
      "Color": 6,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon66",
      "IconSvg": "assets/icons/Icon66.svg",
      "IconPng": "assets/icons_png/Icon66.png"
    },
    {
      "Floor": 67,
      "ID": 67,
      "Color": 6,
      "Shape": 5,
      "Texture": 1,
      "Icon": "Icon67",
      "IconSvg": "assets/icons/Icon67.svg",
      "IconPng": "assets/icons_png/Icon67.png"
    },
    {
      "Floor": 68,
      "ID": 68,
      "Color": 6,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon68",
      "IconSvg": "assets/icons/Icon68.svg",
      "IconPng": "assets/icons_png/Icon68.png"
    },
    {
      "Floor": 69,
      "ID": 69,
      "Color": 6,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon69",
      "IconSvg": "assets/icons/Icon69.svg",
      "IconPng": "assets/icons_png/Icon69.png"
    },
    {
      "Floor": 70,
      "ID": 70,
      "Color": 6,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon70",
      "IconSvg": "assets/icons/Icon70.svg",
      "IconPng": "assets/icons_png/Icon70.png"
    },
    {
      "Floor": 71,
      "ID": 71,
      "Color": 6,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon71",
      "IconSvg": "assets/icons/Icon71.svg",
      "IconPng": "assets/icons_png/Icon71.png"
    },
    {
      "Floor": 72,
      "ID": 72,
      "Color": 6,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon72",
      "IconSvg": "assets/icons/Icon72.svg",
      "IconPng": "assets/icons_png/Icon72.png"
    },
    {
      "Floor": 73,
      "ID": 73,
      "Color": 6,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon73",
      "IconSvg": "assets/icons/Icon73.svg",
      "IconPng": "assets/icons_png/Icon73.png"
    },
    {
      "Floor": 74,
      "ID": 74,
      "Color": 6,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon74",
      "IconSvg": "assets/icons/Icon74.svg",
      "IconPng": "assets/icons_png/Icon74.png"
    },
    {
      "Floor": 75,
      "ID": 75,
      "Color": 6,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon75",
      "IconSvg": "assets/icons/Icon75.svg",
      "IconPng": "assets/icons_png/Icon75.png"
    },
    {
      "Floor": 76,
      "ID": 76,
      "Color": 7,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon76",
      "IconSvg": "assets/icons/Icon76.svg",
      "IconPng": "assets/icons_png/Icon76.png"
    },
    {
      "Floor": 77,
      "ID": 77,
      "Color": 7,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon77",
      "IconSvg": "assets/icons/Icon77.svg",
      "IconPng": "assets/icons_png/Icon77.png"
    },
    {
      "Floor": 78,
      "ID": 78,
      "Color": 7,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon78",
      "IconSvg": "assets/icons/Icon78.svg",
      "IconPng": "assets/icons_png/Icon78.png"
    },
    {
      "Floor": 79,
      "ID": 79,
      "Color": 7,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon79",
      "IconSvg": "assets/icons/Icon79.svg",
      "IconPng": "assets/icons_png/Icon79.png"
    },
    {
      "Floor": 80,
      "ID": 80,
      "Color": 7,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon80",
      "IconSvg": "assets/icons/Icon80.svg",
      "IconPng": "assets/icons_png/Icon80.png"
    },
    {
      "Floor": 81,
      "ID": 81,
      "Color": 7,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon81",
      "IconSvg": "assets/icons/Icon81.svg",
      "IconPng": "assets/icons_png/Icon81.png"
    },
    {
      "Floor": 82,
      "ID": 82,
      "Color": 7,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon82",
      "IconSvg": "assets/icons/Icon82.svg",
      "IconPng": "assets/icons_png/Icon82.png"
    },
    {
      "Floor": 83,
      "ID": 83,
      "Color": 7,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon83",
      "IconSvg": "assets/icons/Icon83.svg",
      "IconPng": "assets/icons_png/Icon83.png"
    },
    {
      "Floor": 84,
      "ID": 84,
      "Color": 7,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon84",
      "IconSvg": "assets/icons/Icon84.svg",
      "IconPng": "assets/icons_png/Icon84.png"
    },
    {
      "Floor": 85,
      "ID": 85,
      "Color": 7,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon85",
      "IconSvg": "assets/icons/Icon85.svg",
      "IconPng": "assets/icons_png/Icon85.png"
    },
    {
      "Floor": 86,
      "ID": 86,
      "Color": 7,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon86",
      "IconSvg": "assets/icons/Icon86.svg",
      "IconPng": "assets/icons_png/Icon86.png"
    },
    {
      "Floor": 87,
      "ID": 87,
      "Color": 7,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon87",
      "IconSvg": "assets/icons/Icon87.svg",
      "IconPng": "assets/icons_png/Icon87.png"
    },
    {
      "Floor": 88,
      "ID": 88,
      "Color": 8,
      "Shape": 1,
      "Texture": 1,
      "Icon": "Icon88",
      "IconSvg": "assets/icons/Icon88.svg",
      "IconPng": "assets/icons_png/Icon88.png"
    },
    {
      "Floor": 89,
      "ID": 89,
      "Color": 8,
      "Shape": 2,
      "Texture": 1,
      "Icon": "Icon89",
      "IconSvg": "assets/icons/Icon89.svg",
      "IconPng": "assets/icons_png/Icon89.png"
    },
    {
      "Floor": 90,
      "ID": 90,
      "Color": 8,
      "Shape": 3,
      "Texture": 1,
      "Icon": "Icon90",
      "IconSvg": "assets/icons/Icon90.svg",
      "IconPng": "assets/icons_png/Icon90.png"
    },
    {
      "Floor": 91,
      "ID": 91,
      "Color": 8,
      "Shape": 4,
      "Texture": 1,
      "Icon": "Icon91",
      "IconSvg": "assets/icons/Icon91.svg",
      "IconPng": "assets/icons_png/Icon91.png"
    },
    {
      "Floor": 92,
      "ID": 92,
      "Color": 8,
      "Shape": 5,
      "Texture": 1,
      "Icon": "Icon92",
      "IconSvg": "assets/icons/Icon92.svg",
      "IconPng": "assets/icons_png/Icon92.png"
    },
    {
      "Floor": 93,
      "ID": 93,
      "Color": 8,
      "Shape": 1,
      "Texture": 2,
      "Icon": "Icon93",
      "IconSvg": "assets/icons/Icon93.svg",
      "IconPng": "assets/icons_png/Icon93.png"
    },
    {
      "Floor": 94,
      "ID": 94,
      "Color": 8,
      "Shape": 2,
      "Texture": 2,
      "Icon": "Icon94",
      "IconSvg": "assets/icons/Icon94.svg",
      "IconPng": "assets/icons_png/Icon94.png"
    },
    {
      "Floor": 95,
      "ID": 95,
      "Color": 8,
      "Shape": 3,
      "Texture": 2,
      "Icon": "Icon95",
      "IconSvg": "assets/icons/Icon95.svg",
      "IconPng": "assets/icons_png/Icon95.png"
    },
    {
      "Floor": 96,
      "ID": 96,
      "Color": 8,
      "Shape": 4,
      "Texture": 2,
      "Icon": "Icon96",
      "IconSvg": "assets/icons/Icon96.svg",
      "IconPng": "assets/icons_png/Icon96.png"
    },
    {
      "Floor": 97,
      "ID": 97,
      "Color": 8,
      "Shape": 1,
      "Texture": 3,
      "Icon": "Icon97",
      "IconSvg": "assets/icons/Icon97.svg",
      "IconPng": "assets/icons_png/Icon97.png"
    },
    {
      "Floor": 98,
      "ID": 98,
      "Color": 8,
      "Shape": 2,
      "Texture": 3,
      "Icon": "Icon98",
      "IconSvg": "assets/icons/Icon98.svg",
      "IconPng": "assets/icons_png/Icon98.png"
    },
    {
      "Floor": 99,
      "ID": 99,
      "Color": 8,
      "Shape": 3,
      "Texture": 3,
      "Icon": "Icon99",
      "IconSvg": "assets/icons/Icon99.svg",
      "IconPng": "assets/icons_png/Icon99.png"
    },
    {
      "Floor": 100,
      "ID": 100,
      "Color": 8,
      "Shape": 4,
      "Texture": 3,
      "Icon": "Icon100",
      "IconSvg": "assets/icons/Icon100.svg",
      "IconPng": "assets/icons_png/Icon100.png"
    }
  ],
  "versions": {
    "child": {
      "label": "儿童版",
      "defaultTrainingSeconds": 180,
      "defaultStartLevel": 1,
      "levels": [
        {
          "ID": 1,
          "Level": 1,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 104,
          "Score": 10,
          "Scores": 60,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 60,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 60,
          "RewardScore": 10
        },
        {
          "ID": 2,
          "Level": 2,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 108,
          "Score": 10,
          "Scores": 60,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 60,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 60,
          "RewardScore": 10
        },
        {
          "ID": 3,
          "Level": 3,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 112,
          "Score": 11,
          "Scores": 66,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 66,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 66,
          "RewardScore": 11
        },
        {
          "ID": 4,
          "Level": 4,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 116,
          "Score": 11,
          "Scores": 66,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 66,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 66,
          "RewardScore": 11
        },
        {
          "ID": 5,
          "Level": 5,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 120,
          "Score": 12,
          "Scores": 72,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 72,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 72,
          "RewardScore": 12
        },
        {
          "ID": 6,
          "Level": 6,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 124,
          "Score": 12,
          "Scores": 72,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 72,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 72,
          "RewardScore": 12
        },
        {
          "ID": 7,
          "Level": 7,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 128,
          "Score": 13,
          "Scores": 78,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 78,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 78,
          "RewardScore": 13
        },
        {
          "ID": 8,
          "Level": 8,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 132,
          "Score": 13,
          "Scores": 78,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 78,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 78,
          "RewardScore": 13
        },
        {
          "ID": 9,
          "Level": 9,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 136,
          "Score": 14,
          "Scores": 84,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 84,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 84,
          "RewardScore": 14
        },
        {
          "ID": 10,
          "Level": 10,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 140,
          "Score": 14,
          "Scores": 84,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 84,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 84,
          "RewardScore": 14
        },
        {
          "ID": 11,
          "Level": 11,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 144,
          "Score": 15,
          "Scores": 120,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 120,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 120,
          "RewardScore": 15
        },
        {
          "ID": 12,
          "Level": 12,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 148,
          "Score": 15,
          "Scores": 120,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 120,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 120,
          "RewardScore": 15
        },
        {
          "ID": 13,
          "Level": 13,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 152,
          "Score": 16,
          "Scores": 128,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 128,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 128,
          "RewardScore": 16
        },
        {
          "ID": 14,
          "Level": 14,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 156,
          "Score": 16,
          "Scores": 128,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 128,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 128,
          "RewardScore": 16
        },
        {
          "ID": 15,
          "Level": 15,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 160,
          "Score": 17,
          "Scores": 136,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 136,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 136,
          "RewardScore": 17
        },
        {
          "ID": 16,
          "Level": 16,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 164,
          "Score": 17,
          "Scores": 170,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 170,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 170,
          "RewardScore": 17
        },
        {
          "ID": 17,
          "Level": 17,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 168,
          "Score": 18,
          "Scores": 180,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 180,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 180,
          "RewardScore": 18
        },
        {
          "ID": 18,
          "Level": 18,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 172,
          "Score": 18,
          "Scores": 180,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 180,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 180,
          "RewardScore": 18
        },
        {
          "ID": 19,
          "Level": 19,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 176,
          "Score": 19,
          "Scores": 190,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 190,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 190,
          "RewardScore": 19
        },
        {
          "ID": 20,
          "Level": 20,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 180,
          "Score": 19,
          "Scores": 190,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 190,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 190,
          "RewardScore": 19
        },
        {
          "ID": 21,
          "Level": 21,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 184,
          "Score": 20,
          "Scores": 250,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 275,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 250,
          "RewardScore": 20
        },
        {
          "ID": 22,
          "Level": 22,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 188,
          "Score": 20,
          "Scores": 250,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 275,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 250,
          "RewardScore": 20
        },
        {
          "ID": 23,
          "Level": 23,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 192,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 24,
          "Level": 24,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 196,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 25,
          "Level": 25,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 200,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 26,
          "Level": 26,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 204,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 27,
          "Level": 27,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 208,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 28,
          "Level": 28,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 212,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 29,
          "Level": 29,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 216,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 30,
          "Level": 30,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 220,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 31,
          "Level": 31,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 224,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 32,
          "Level": 32,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 228,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 33,
          "Level": 33,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 232,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 34,
          "Level": 34,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 236,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 35,
          "Level": 35,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 240,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 36,
          "Level": 36,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 244,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 37,
          "Level": 37,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 248,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 38,
          "Level": 38,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 252,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 39,
          "Level": 39,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 256,
          "Score": 25,
          "Scores": 450,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 495,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 450,
          "RewardScore": 25
        },
        {
          "ID": 40,
          "Level": 40,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 260,
          "Score": 25,
          "Scores": 450,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 495,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 450,
          "RewardScore": 25
        },
        {
          "ID": 41,
          "Level": 41,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 264,
          "Score": 25,
          "Scores": 600,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 720,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 600,
          "RewardScore": 25
        },
        {
          "ID": 42,
          "Level": 42,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 268,
          "Score": 25,
          "Scores": 600,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 720,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 600,
          "RewardScore": 25
        },
        {
          "ID": 43,
          "Level": 43,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 272,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 44,
          "Level": 44,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 276,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 45,
          "Level": 45,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 280,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 46,
          "Level": 46,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 284,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 47,
          "Level": 47,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 288,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        },
        {
          "ID": 48,
          "Level": 48,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 292,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        },
        {
          "ID": 49,
          "Level": 49,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 296,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        },
        {
          "ID": 50,
          "Level": 50,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 300,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        }
      ],
      "configSource": "uploaded data(1).json / P2快闪图形.xlsm",
      "autoContinueMs": 850,
      "firstCardMs": 1000,
      "defaultDifficulty": "easy",
      "difficultyPresets": [
        {
          "id": "easy",
          "label": "容易",
          "startLevel": 1,
          "description": "从第1关开始"
        },
        {
          "id": "normal",
          "label": "普通",
          "startLevel": 15,
          "description": "从第15关开始"
        },
        {
          "id": "hard",
          "label": "困难",
          "startLevel": 30,
          "description": "从第30关开始"
        }
      ]
    },
    "adult": {
      "label": "成人版",
      "defaultTrainingSeconds": 180,
      "defaultStartLevel": 1,
      "levels": [
        {
          "ID": 1,
          "Level": 1,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 104,
          "Score": 10,
          "Scores": 60,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 60,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 60,
          "RewardScore": 10
        },
        {
          "ID": 2,
          "Level": 2,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 108,
          "Score": 10,
          "Scores": 60,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 60,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 60,
          "RewardScore": 10
        },
        {
          "ID": 3,
          "Level": 3,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 112,
          "Score": 11,
          "Scores": 66,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 66,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 66,
          "RewardScore": 11
        },
        {
          "ID": 4,
          "Level": 4,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 116,
          "Score": 11,
          "Scores": 66,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 66,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 66,
          "RewardScore": 11
        },
        {
          "ID": 5,
          "Level": 5,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 120,
          "Score": 12,
          "Scores": 72,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 72,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 72,
          "RewardScore": 12
        },
        {
          "ID": 6,
          "Level": 6,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 124,
          "Score": 12,
          "Scores": 72,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 72,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 72,
          "RewardScore": 12
        },
        {
          "ID": 7,
          "Level": 7,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 128,
          "Score": 13,
          "Scores": 78,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 78,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 78,
          "RewardScore": 13
        },
        {
          "ID": 8,
          "Level": 8,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 132,
          "Score": 13,
          "Scores": 78,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 78,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 78,
          "RewardScore": 13
        },
        {
          "ID": 9,
          "Level": 9,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 136,
          "Score": 14,
          "Scores": 84,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 84,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 84,
          "RewardScore": 14
        },
        {
          "ID": 10,
          "Level": 10,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 2,
          "Time": 20,
          "Brains": 140,
          "Score": 14,
          "Scores": 84,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 84,
          "TargetCount": 6,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 84,
          "RewardScore": 14
        },
        {
          "ID": 11,
          "Level": 11,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 144,
          "Score": 15,
          "Scores": 120,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 120,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 120,
          "RewardScore": 15
        },
        {
          "ID": 12,
          "Level": 12,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 148,
          "Score": 15,
          "Scores": 120,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 120,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 120,
          "RewardScore": 15
        },
        {
          "ID": 13,
          "Level": 13,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 152,
          "Score": 16,
          "Scores": 128,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 128,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 128,
          "RewardScore": 16
        },
        {
          "ID": 14,
          "Level": 14,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 156,
          "Score": 16,
          "Scores": 128,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 128,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 128,
          "RewardScore": 16
        },
        {
          "ID": 15,
          "Level": 15,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 20,
          "Brains": 160,
          "Score": 17,
          "Scores": 136,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 136,
          "TargetCount": 8,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 136,
          "RewardScore": 17
        },
        {
          "ID": 16,
          "Level": 16,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 164,
          "Score": 17,
          "Scores": 170,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 170,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 170,
          "RewardScore": 17
        },
        {
          "ID": 17,
          "Level": 17,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 168,
          "Score": 18,
          "Scores": 180,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 180,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 180,
          "RewardScore": 18
        },
        {
          "ID": 18,
          "Level": 18,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 172,
          "Score": 18,
          "Scores": 180,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 180,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 180,
          "RewardScore": 18
        },
        {
          "ID": 19,
          "Level": 19,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 176,
          "Score": 19,
          "Scores": 190,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 190,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 190,
          "RewardScore": 19
        },
        {
          "ID": 20,
          "Level": 20,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 3,
          "Time": 25,
          "Brains": 180,
          "Score": 19,
          "Scores": 190,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 190,
          "TargetCount": 10,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 190,
          "RewardScore": 19
        },
        {
          "ID": 21,
          "Level": 21,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 184,
          "Score": 20,
          "Scores": 250,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 275,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 250,
          "RewardScore": 20
        },
        {
          "ID": 22,
          "Level": 22,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 188,
          "Score": 20,
          "Scores": 250,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 275,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 250,
          "RewardScore": 20
        },
        {
          "ID": 23,
          "Level": 23,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 192,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 24,
          "Level": 24,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 196,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 25,
          "Level": 25,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 200,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 1,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 26,
          "Level": 26,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 204,
          "Score": 21,
          "Scores": 263,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 289,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 263,
          "RewardScore": 21
        },
        {
          "ID": 27,
          "Level": 27,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 208,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 28,
          "Level": 28,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 212,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 29,
          "Level": 29,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 216,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 30,
          "Level": 30,
          "Rate": 50,
          "Type": 1,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 4,
          "Time": 25,
          "Brains": 220,
          "Score": 22,
          "Scores": 275,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 303,
          "TargetCount": 13,
          "ShapeRange": [
            1,
            30
          ],
          "PassScore": 275,
          "RewardScore": 22
        },
        {
          "ID": 31,
          "Level": 31,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 224,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 32,
          "Level": 32,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 228,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 33,
          "Level": 33,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 232,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 34,
          "Level": 34,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 236,
          "Score": 23,
          "Scores": 414,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 456,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 414,
          "RewardScore": 23
        },
        {
          "ID": 35,
          "Level": 35,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 240,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 36,
          "Level": 36,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 244,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 37,
          "Level": 37,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 248,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 38,
          "Level": 38,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 252,
          "Score": 24,
          "Scores": 432,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 476,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 432,
          "RewardScore": 24
        },
        {
          "ID": 39,
          "Level": 39,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 256,
          "Score": 25,
          "Scores": 450,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 495,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 450,
          "RewardScore": 25
        },
        {
          "ID": 40,
          "Level": 40,
          "Rate": 50,
          "Type": 2,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 5,
          "Time": 30,
          "Brains": 260,
          "Score": 25,
          "Scores": 450,
          "Reward": 1,
          "RewardNum": 2,
          "Limit": 495,
          "TargetCount": 18,
          "ShapeRange": [
            31,
            62
          ],
          "PassScore": 450,
          "RewardScore": 25
        },
        {
          "ID": 41,
          "Level": 41,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 264,
          "Score": 25,
          "Scores": 600,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 720,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 600,
          "RewardScore": 25
        },
        {
          "ID": 42,
          "Level": 42,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 268,
          "Score": 25,
          "Scores": 600,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 720,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 600,
          "RewardScore": 25
        },
        {
          "ID": 43,
          "Level": 43,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 272,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 44,
          "Level": 44,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 276,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 45,
          "Level": 45,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 280,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 46,
          "Level": 46,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 284,
          "Score": 26,
          "Scores": 624,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 749,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 624,
          "RewardScore": 26
        },
        {
          "ID": 47,
          "Level": 47,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 288,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        },
        {
          "ID": 48,
          "Level": 48,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 292,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        },
        {
          "ID": 49,
          "Level": 49,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 296,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        },
        {
          "ID": 50,
          "Level": 50,
          "Rate": 50,
          "Type": 3,
          "MissionNum": 1,
          "MissionPass": 1,
          "Fault": 6,
          "Time": 30,
          "Brains": 300,
          "Score": 27,
          "Scores": 648,
          "Reward": 1,
          "RewardNum": 3,
          "Limit": 778,
          "TargetCount": 24,
          "ShapeRange": [
            63,
            100
          ],
          "PassScore": 648,
          "RewardScore": 27
        }
      ],
      "configSource": "uploaded data(1).json / P2快闪图形.xlsm",
      "autoContinueMs": 850,
      "firstCardMs": 1000,
      "defaultDifficulty": "easy",
      "difficultyPresets": [
        {
          "id": "easy",
          "label": "容易",
          "startLevel": 1,
          "description": "从第1关开始"
        },
        {
          "id": "normal",
          "label": "普通",
          "startLevel": 15,
          "description": "从第15关开始"
        },
        {
          "id": "hard",
          "label": "困难",
          "startLevel": 30,
          "description": "从第30关开始"
        }
      ]
    }
  },
  "misc": {
    "Columes": [
      "Key"
    ],
    "Values": [
      [
        50
      ]
    ]
  }
};
