globalThis.SILENT_POND_CONFIG = {
  "gameTitle": "静默池塘",
  "sourceWorkbook": "P2静默池塘(1).xlsm",
  "totalLevels": 50,
  "turnTime": {
    "min": 1.4,
    "max": 3.6,
    "note": "规范要求可配置变向时间上下限；数值表未提供该字段，原型使用全局默认值，可在此修改。"
  },
  "fishSize": {
    "redPercent": 100,
    "blackPercent": 100,
    "note": "规范列出鱼体型配置项；数值表未提供该字段，运行时读取此处默认百分比，也兼容关卡级 RedSize/BlackSize 等字段。"
  },
  "faultPolicy": "allowed_mistakes",
  "faultPolicyNote": "Fault 按“可错次数”解释：错误次数超过 Fault 才失败；例如 Fault=2 表示前两次错误可容错，第 3 次错误失败。",
  "levels": [
    {
      "记录号": 1,
      "ID": 1,
      "Level": 1,
      "Shade": 0,
      "RedNum": 2,
      "BlackNum": 1,
      "Speed": 80,
      "SpaceTime": 1,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 104,
      "Score": 100,
      "Scores": 10,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 2,
      "ID": 2,
      "Level": 2,
      "Shade": 0,
      "RedNum": 2,
      "BlackNum": 1,
      "Speed": 80,
      "SpaceTime": 1.2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 108,
      "Score": 105,
      "Scores": 10,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 3,
      "ID": 3,
      "Level": 3,
      "Shade": 0,
      "RedNum": 2,
      "BlackNum": 1,
      "Speed": 81,
      "SpaceTime": 1.3,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 112,
      "Score": 110,
      "Scores": 10,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 4,
      "ID": 4,
      "Level": 4,
      "Shade": 0,
      "RedNum": 3,
      "BlackNum": 1,
      "Speed": 81,
      "SpaceTime": 1.5,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 116,
      "Score": 115,
      "Scores": 10,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 5,
      "ID": 5,
      "Level": 5,
      "Shade": 0,
      "RedNum": 3,
      "BlackNum": 1,
      "Speed": 82,
      "SpaceTime": 1.6,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 120,
      "Score": 120,
      "Scores": 10,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 6,
      "ID": 6,
      "Level": 6,
      "Shade": 0,
      "RedNum": 3,
      "BlackNum": 1,
      "Speed": 82,
      "SpaceTime": 1.7,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 124,
      "Score": 135,
      "Scores": 11,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 7,
      "ID": 7,
      "Level": 7,
      "Shade": 0,
      "RedNum": 3,
      "BlackNum": 1,
      "Speed": 83,
      "SpaceTime": 1.7,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 128,
      "Score": 140,
      "Scores": 11,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 8,
      "ID": 8,
      "Level": 8,
      "Shade": 0,
      "RedNum": 3,
      "BlackNum": 1,
      "Speed": 83,
      "SpaceTime": 1.8,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 132,
      "Score": 145,
      "Scores": 11,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 9,
      "ID": 9,
      "Level": 9,
      "Shade": 0,
      "RedNum": 3,
      "BlackNum": 2,
      "Speed": 84,
      "SpaceTime": 1.9,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 136,
      "Score": 150,
      "Scores": 11,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 10,
      "ID": 10,
      "Level": 10,
      "Shade": 0,
      "RedNum": 3,
      "BlackNum": 2,
      "Speed": 84,
      "SpaceTime": 1.9,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 140,
      "Score": 155,
      "Scores": 11,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 11,
      "ID": 11,
      "Level": 11,
      "Shade": 1,
      "RedNum": 3,
      "BlackNum": 2,
      "Speed": 85,
      "SpaceTime": 1.9,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 144,
      "Score": 170,
      "Scores": 12,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 12,
      "ID": 12,
      "Level": 12,
      "Shade": 1,
      "RedNum": 3,
      "BlackNum": 2,
      "Speed": 85,
      "SpaceTime": 2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 148,
      "Score": 175,
      "Scores": 12,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 13,
      "ID": 13,
      "Level": 13,
      "Shade": 1,
      "RedNum": 3,
      "BlackNum": 2,
      "Speed": 86,
      "SpaceTime": 2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 30,
      "Brains": 152,
      "Score": 180,
      "Scores": 12,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 14,
      "ID": 14,
      "Level": 14,
      "Shade": 1,
      "RedNum": 4,
      "BlackNum": 1,
      "Speed": 86,
      "SpaceTime": 2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 156,
      "Score": 185,
      "Scores": 12,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 15,
      "ID": 15,
      "Level": 15,
      "Shade": 1,
      "RedNum": 4,
      "BlackNum": 1,
      "Speed": 87,
      "SpaceTime": 2.1,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 160,
      "Score": 190,
      "Scores": 12,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 16,
      "ID": 16,
      "Level": 16,
      "Shade": 1,
      "RedNum": 4,
      "BlackNum": 1,
      "Speed": 87,
      "SpaceTime": 2.1,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 164,
      "Score": 205,
      "Scores": 13,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 17,
      "ID": 17,
      "Level": 17,
      "Shade": 1,
      "RedNum": 4,
      "BlackNum": 1,
      "Speed": 88,
      "SpaceTime": 2.2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 168,
      "Score": 210,
      "Scores": 13,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 18,
      "ID": 18,
      "Level": 18,
      "Shade": 1,
      "RedNum": 4,
      "BlackNum": 1,
      "Speed": 88,
      "SpaceTime": 2.3,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 172,
      "Score": 215,
      "Scores": 13,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 19,
      "ID": 19,
      "Level": 19,
      "Shade": 1,
      "RedNum": 4,
      "BlackNum": 1,
      "Speed": 89,
      "SpaceTime": 2.3,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 176,
      "Score": 220,
      "Scores": 13,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 20,
      "ID": 20,
      "Level": 20,
      "Shade": 1,
      "RedNum": 4,
      "BlackNum": 2,
      "Speed": 89,
      "SpaceTime": 2.4,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 180,
      "Score": 225,
      "Scores": 13,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 21,
      "ID": 21,
      "Level": 21,
      "Shade": 2,
      "RedNum": 4,
      "BlackNum": 2,
      "Speed": 90,
      "SpaceTime": 2.4,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 184,
      "Score": 240,
      "Scores": 14,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 22,
      "ID": 22,
      "Level": 22,
      "Shade": 2,
      "RedNum": 4,
      "BlackNum": 2,
      "Speed": 90,
      "SpaceTime": 2.5,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 188,
      "Score": 245,
      "Scores": 14,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 23,
      "ID": 23,
      "Level": 23,
      "Shade": 2,
      "RedNum": 4,
      "BlackNum": 2,
      "Speed": 91,
      "SpaceTime": 2.5,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 192,
      "Score": 250,
      "Scores": 14,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 24,
      "ID": 24,
      "Level": 24,
      "Shade": 2,
      "RedNum": 4,
      "BlackNum": 2,
      "Speed": 91,
      "SpaceTime": 2.5,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 196,
      "Score": 255,
      "Scores": 14,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 25,
      "ID": 25,
      "Level": 25,
      "Shade": 2,
      "RedNum": 4,
      "BlackNum": 2,
      "Speed": 92,
      "SpaceTime": 2.6,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 45,
      "Brains": 200,
      "Score": 260,
      "Scores": 14,
      "Reward": 1,
      "RewardNum": 1,
      "Limit": 1
    },
    {
      "记录号": 26,
      "ID": 26,
      "Level": 26,
      "Shade": 2,
      "RedNum": 5,
      "BlackNum": 1,
      "Speed": 92,
      "SpaceTime": 2.6,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 204,
      "Score": 275,
      "Scores": 15,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 27,
      "ID": 27,
      "Level": 27,
      "Shade": 2,
      "RedNum": 5,
      "BlackNum": 1,
      "Speed": 93,
      "SpaceTime": 2.7,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 208,
      "Score": 280,
      "Scores": 15,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 28,
      "ID": 28,
      "Level": 28,
      "Shade": 2,
      "RedNum": 5,
      "BlackNum": 1,
      "Speed": 93,
      "SpaceTime": 2.7,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 212,
      "Score": 285,
      "Scores": 15,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 29,
      "ID": 29,
      "Level": 29,
      "Shade": 2,
      "RedNum": 5,
      "BlackNum": 1,
      "Speed": 94,
      "SpaceTime": 2.8,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 216,
      "Score": 290,
      "Scores": 15,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 30,
      "ID": 30,
      "Level": 30,
      "Shade": 2,
      "RedNum": 5,
      "BlackNum": 1,
      "Speed": 94,
      "SpaceTime": 2.9,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 220,
      "Score": 295,
      "Scores": 15,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 31,
      "ID": 31,
      "Level": 31,
      "Shade": 3,
      "RedNum": 5,
      "BlackNum": 1,
      "Speed": 95,
      "SpaceTime": 2.9,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 224,
      "Score": 310,
      "Scores": 16,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 32,
      "ID": 32,
      "Level": 32,
      "Shade": 3,
      "RedNum": 5,
      "BlackNum": 2,
      "Speed": 95,
      "SpaceTime": 3,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 228,
      "Score": 315,
      "Scores": 16,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 33,
      "ID": 33,
      "Level": 33,
      "Shade": 3,
      "RedNum": 5,
      "BlackNum": 2,
      "Speed": 96,
      "SpaceTime": 3,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 232,
      "Score": 320,
      "Scores": 16,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 34,
      "ID": 34,
      "Level": 34,
      "Shade": 3,
      "RedNum": 5,
      "BlackNum": 2,
      "Speed": 96,
      "SpaceTime": 3.1,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 236,
      "Score": 325,
      "Scores": 16,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 35,
      "ID": 35,
      "Level": 35,
      "Shade": 3,
      "RedNum": 5,
      "BlackNum": 2,
      "Speed": 97,
      "SpaceTime": 3.1,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 240,
      "Score": 330,
      "Scores": 16,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 36,
      "ID": 36,
      "Level": 36,
      "Shade": 3,
      "RedNum": 5,
      "BlackNum": 2,
      "Speed": 97,
      "SpaceTime": 3.1,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 244,
      "Score": 345,
      "Scores": 17,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 37,
      "ID": 37,
      "Level": 37,
      "Shade": 3,
      "RedNum": 5,
      "BlackNum": 2,
      "Speed": 98,
      "SpaceTime": 3.2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 60,
      "Brains": 248,
      "Score": 350,
      "Scores": 17,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 38,
      "ID": 38,
      "Level": 38,
      "Shade": 3,
      "RedNum": 6,
      "BlackNum": 1,
      "Speed": 98,
      "SpaceTime": 3.2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 252,
      "Score": 355,
      "Scores": 17,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 39,
      "ID": 39,
      "Level": 39,
      "Shade": 3,
      "RedNum": 6,
      "BlackNum": 1,
      "Speed": 99,
      "SpaceTime": 3.3,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 256,
      "Score": 360,
      "Scores": 17,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 40,
      "ID": 40,
      "Level": 40,
      "Shade": 3,
      "RedNum": 6,
      "BlackNum": 1,
      "Speed": 99,
      "SpaceTime": 3.4,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 260,
      "Score": 365,
      "Scores": 17,
      "Reward": 1,
      "RewardNum": 2,
      "Limit": 4
    },
    {
      "记录号": 41,
      "ID": 41,
      "Level": 41,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 1,
      "Speed": 100,
      "SpaceTime": 3.4,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 264,
      "Score": 380,
      "Scores": 18,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 42,
      "ID": 42,
      "Level": 42,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 1,
      "Speed": 100,
      "SpaceTime": 3.5,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 268,
      "Score": 385,
      "Scores": 18,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 43,
      "ID": 43,
      "Level": 43,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 2,
      "Speed": 101,
      "SpaceTime": 3.6,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 272,
      "Score": 390,
      "Scores": 18,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 44,
      "ID": 44,
      "Level": 44,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 2,
      "Speed": 101,
      "SpaceTime": 3.7,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 276,
      "Score": 395,
      "Scores": 18,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 45,
      "ID": 45,
      "Level": 45,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 2,
      "Speed": 102,
      "SpaceTime": 3.8,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 280,
      "Score": 400,
      "Scores": 18,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 46,
      "ID": 46,
      "Level": 46,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 2,
      "Speed": 102,
      "SpaceTime": 3.8,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 284,
      "Score": 415,
      "Scores": 19,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 47,
      "ID": 47,
      "Level": 47,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 2,
      "Speed": 103,
      "SpaceTime": 3.9,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 288,
      "Score": 420,
      "Scores": 19,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 48,
      "ID": 48,
      "Level": 48,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 3,
      "Speed": 103,
      "SpaceTime": 4,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 292,
      "Score": 425,
      "Scores": 19,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 49,
      "ID": 49,
      "Level": 49,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 3,
      "Speed": 104,
      "SpaceTime": 4.1,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 296,
      "Score": 430,
      "Scores": 19,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    },
    {
      "记录号": 50,
      "ID": 50,
      "Level": 50,
      "Shade": 4,
      "RedNum": 6,
      "BlackNum": 3,
      "Speed": 104,
      "SpaceTime": 4.2,
      "MissionNum": 1,
      "MissionPass": 1,
      "Fault": 2,
      "Time": 80,
      "Brains": 300,
      "Score": 435,
      "Scores": 19,
      "Reward": 1,
      "RewardNum": 3,
      "Limit": 7
    }
  ]
};
