window.GAME_CONFIG = {
  "title": "眼疾手快",
  "version": "成人版 · 三难度窗口适配版",
  "mode": "adult",
  "defaultDurationSeconds": 300,
  "maxLevel": 51,
  "themeColor": "#65a9a4",
  "difficultyNote": "成人版沿用儿童版同字段配置格式，但通关目标更高、出现节奏更快，干扰物占比略高。",
  "assetStyle": "self-made polished vector assets, no external network resources",
  "schema": [
    "ID",
    "Level",
    "Num",
    "LineCount",
    "LineSpace",
    "CountMax",
    "CountMin",
    "Time",
    "Normal",
    "Helmet",
    "Bomb",
    "White",
    "Other",
    "Fault",
    "LevelTime",
    "Brains",
    "Score",
    "PassScore",
    "Reward",
    "RewardNum",
    "Limit",
    "PassTarget"
  ],
  "levels": [
    {
      "id": 1,
      "level": 1,
      "num": "3*3",
      "cols": 3,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2230,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3500,
      "probability": {
        "normal": 72,
        "helmet": 84,
        "bomb": 91,
        "white": 97,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 104,
      "answerScore": 11,
      "passScore": 156,
      "passTarget": 15,
      "rewardScore": 11,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 156
    },
    {
      "id": 2,
      "level": 2,
      "num": "3*3",
      "cols": 3,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2189,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3425,
      "probability": {
        "normal": 72,
        "helmet": 84,
        "bomb": 91,
        "white": 97,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 108,
      "answerScore": 12,
      "passScore": 172,
      "passTarget": 15,
      "rewardScore": 12,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 172
    },
    {
      "id": 3,
      "level": 3,
      "num": "3*3",
      "cols": 3,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2149,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3350,
      "probability": {
        "normal": 72,
        "helmet": 84,
        "bomb": 91,
        "white": 97,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 112,
      "answerScore": 13,
      "passScore": 187,
      "passTarget": 15,
      "rewardScore": 13,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 187
    },
    {
      "id": 4,
      "level": 4,
      "num": "3*3",
      "cols": 3,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2108,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3275,
      "probability": {
        "normal": 71,
        "helmet": 84,
        "bomb": 91,
        "white": 97,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 116,
      "answerScore": 14,
      "passScore": 203,
      "passTarget": 15,
      "rewardScore": 14,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 203
    },
    {
      "id": 5,
      "level": 5,
      "num": "3*3",
      "cols": 3,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2068,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3200,
      "probability": {
        "normal": 71,
        "helmet": 84,
        "bomb": 91,
        "white": 97,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 120,
      "answerScore": 15,
      "passScore": 218,
      "passTarget": 15,
      "rewardScore": 15,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 218
    },
    {
      "id": 6,
      "level": 6,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2257,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3550,
      "probability": {
        "normal": 71,
        "helmet": 84,
        "bomb": 91,
        "white": 97,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 124,
      "answerScore": 16,
      "passScore": 234,
      "passTarget": 15,
      "rewardScore": 16,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 234
    },
    {
      "id": 7,
      "level": 7,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2216,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3475,
      "probability": {
        "normal": 67,
        "helmet": 81,
        "bomb": 89,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 128,
      "answerScore": 17,
      "passScore": 250,
      "passTarget": 15,
      "rewardScore": 17,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 250
    },
    {
      "id": 8,
      "level": 8,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2176,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3400,
      "probability": {
        "normal": 67,
        "helmet": 81,
        "bomb": 89,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 132,
      "answerScore": 18,
      "passScore": 265,
      "passTarget": 15,
      "rewardScore": 18,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 265
    },
    {
      "id": 9,
      "level": 9,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2135,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3325,
      "probability": {
        "normal": 67,
        "helmet": 81,
        "bomb": 89,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 136,
      "answerScore": 19,
      "passScore": 281,
      "passTarget": 15,
      "rewardScore": 19,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 281
    },
    {
      "id": 10,
      "level": 10,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2095,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3250,
      "probability": {
        "normal": 66,
        "helmet": 81,
        "bomb": 89,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 140,
      "answerScore": 20,
      "passScore": 296,
      "passTarget": 15,
      "rewardScore": 20,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 296
    },
    {
      "id": 11,
      "level": 11,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2054,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3175,
      "probability": {
        "normal": 66,
        "helmet": 81,
        "bomb": 89,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 144,
      "answerScore": 21,
      "passScore": 312,
      "passTarget": 15,
      "rewardScore": 21,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 312
    },
    {
      "id": 12,
      "level": 12,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 2014,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3100,
      "probability": {
        "normal": 66,
        "helmet": 81,
        "bomb": 89,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 148,
      "answerScore": 22,
      "passScore": 328,
      "passTarget": 15,
      "rewardScore": 22,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 328
    },
    {
      "id": 13,
      "level": 13,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1973,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 3025,
      "probability": {
        "normal": 66,
        "helmet": 81,
        "bomb": 89,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 152,
      "answerScore": 23,
      "passScore": 343,
      "passTarget": 15,
      "rewardScore": 23,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 343
    },
    {
      "id": 14,
      "level": 14,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1933,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2950,
      "probability": {
        "normal": 63,
        "helmet": 79,
        "bomb": 88,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 156,
      "answerScore": 24,
      "passScore": 359,
      "passTarget": 15,
      "rewardScore": 24,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 359
    },
    {
      "id": 15,
      "level": 15,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1892,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2875,
      "probability": {
        "normal": 63,
        "helmet": 79,
        "bomb": 88,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 160,
      "answerScore": 25,
      "passScore": 374,
      "passTarget": 15,
      "rewardScore": 25,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 374
    },
    {
      "id": 16,
      "level": 16,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1852,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2800,
      "probability": {
        "normal": 63,
        "helmet": 79,
        "bomb": 88,
        "white": 96,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 164,
      "answerScore": 26,
      "passScore": 390,
      "passTarget": 15,
      "rewardScore": 26,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 390
    },
    {
      "id": 17,
      "level": 17,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1811,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2725,
      "probability": {
        "normal": 61,
        "helmet": 78,
        "bomb": 87,
        "white": 95,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 168,
      "answerScore": 27,
      "passScore": 406,
      "passTarget": 16,
      "rewardScore": 27,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 406
    },
    {
      "id": 18,
      "level": 18,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1771,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2650,
      "probability": {
        "normal": 61,
        "helmet": 78,
        "bomb": 87,
        "white": 95,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 172,
      "answerScore": 28,
      "passScore": 421,
      "passTarget": 16,
      "rewardScore": 28,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 421
    },
    {
      "id": 19,
      "level": 19,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1730,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2575,
      "probability": {
        "normal": 61,
        "helmet": 78,
        "bomb": 87,
        "white": 95,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 176,
      "answerScore": 29,
      "passScore": 437,
      "passTarget": 16,
      "rewardScore": 29,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 437
    },
    {
      "id": 20,
      "level": 20,
      "num": "4*3",
      "cols": 4,
      "rows": 3,
      "lineCount": 2,
      "lineSpace": 1690,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2500,
      "probability": {
        "normal": 58,
        "helmet": 76,
        "bomb": 86,
        "white": 95,
        "other": 100
      },
      "fault": 1,
      "roundSeconds": 30,
      "brains": 180,
      "answerScore": 30,
      "passScore": 452,
      "passTarget": 16,
      "rewardScore": 30,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 452
    },
    {
      "id": 21,
      "level": 21,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1879,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2850,
      "probability": {
        "normal": 58,
        "helmet": 76,
        "bomb": 86,
        "white": 95,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 184,
      "answerScore": 31,
      "passScore": 468,
      "passTarget": 16,
      "rewardScore": 31,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 468
    },
    {
      "id": 22,
      "level": 22,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1838,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2775,
      "probability": {
        "normal": 58,
        "helmet": 76,
        "bomb": 86,
        "white": 95,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 188,
      "answerScore": 32,
      "passScore": 484,
      "passTarget": 16,
      "rewardScore": 32,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 484
    },
    {
      "id": 23,
      "level": 23,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1798,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2700,
      "probability": {
        "normal": 58,
        "helmet": 76,
        "bomb": 86,
        "white": 95,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 192,
      "answerScore": 33,
      "passScore": 499,
      "passTarget": 16,
      "rewardScore": 33,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 499
    },
    {
      "id": 24,
      "level": 24,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1757,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2625,
      "probability": {
        "normal": 57,
        "helmet": 76,
        "bomb": 86,
        "white": 95,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 196,
      "answerScore": 34,
      "passScore": 515,
      "passTarget": 16,
      "rewardScore": 34,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 515
    },
    {
      "id": 25,
      "level": 25,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1717,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2550,
      "probability": {
        "normal": 57,
        "helmet": 76,
        "bomb": 86,
        "white": 95,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 200,
      "answerScore": 35,
      "passScore": 530,
      "passTarget": 16,
      "rewardScore": 35,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 530
    },
    {
      "id": 26,
      "level": 26,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1676,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2475,
      "probability": {
        "normal": 57,
        "helmet": 76,
        "bomb": 86,
        "white": 95,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 204,
      "answerScore": 36,
      "passScore": 546,
      "passTarget": 16,
      "rewardScore": 36,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 546
    },
    {
      "id": 27,
      "level": 27,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1636,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2400,
      "probability": {
        "normal": 53,
        "helmet": 73,
        "bomb": 84,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 208,
      "answerScore": 37,
      "passScore": 562,
      "passTarget": 16,
      "rewardScore": 37,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 562
    },
    {
      "id": 28,
      "level": 28,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1595,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2325,
      "probability": {
        "normal": 53,
        "helmet": 73,
        "bomb": 84,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 212,
      "answerScore": 38,
      "passScore": 577,
      "passTarget": 16,
      "rewardScore": 38,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 577
    },
    {
      "id": 29,
      "level": 29,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1555,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2250,
      "probability": {
        "normal": 53,
        "helmet": 73,
        "bomb": 84,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 216,
      "answerScore": 39,
      "passScore": 593,
      "passTarget": 16,
      "rewardScore": 39,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 593
    },
    {
      "id": 30,
      "level": 30,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1514,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2175,
      "probability": {
        "normal": 52,
        "helmet": 73,
        "bomb": 84,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 220,
      "answerScore": 40,
      "passScore": 608,
      "passTarget": 16,
      "rewardScore": 40,
      "rewardType": 1,
      "rewardNum": 1,
      "limit": 608
    },
    {
      "id": 31,
      "level": 31,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1474,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2100,
      "probability": {
        "normal": 52,
        "helmet": 73,
        "bomb": 84,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 224,
      "answerScore": 41,
      "passScore": 624,
      "passTarget": 16,
      "rewardScore": 41,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 624
    },
    {
      "id": 32,
      "level": 32,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1433,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2025,
      "probability": {
        "normal": 52,
        "helmet": 73,
        "bomb": 84,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 228,
      "answerScore": 42,
      "passScore": 640,
      "passTarget": 16,
      "rewardScore": 42,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 640
    },
    {
      "id": 33,
      "level": 33,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1393,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1950,
      "probability": {
        "normal": 52,
        "helmet": 73,
        "bomb": 84,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 232,
      "answerScore": 43,
      "passScore": 655,
      "passTarget": 16,
      "rewardScore": 43,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 655
    },
    {
      "id": 34,
      "level": 34,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1352,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1875,
      "probability": {
        "normal": 50,
        "helmet": 71,
        "bomb": 83,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 236,
      "answerScore": 44,
      "passScore": 671,
      "passTarget": 16,
      "rewardScore": 44,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 671
    },
    {
      "id": 35,
      "level": 35,
      "num": "4*4",
      "cols": 4,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1312,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1800,
      "probability": {
        "normal": 50,
        "helmet": 71,
        "bomb": 83,
        "white": 94,
        "other": 100
      },
      "fault": 2,
      "roundSeconds": 30,
      "brains": 240,
      "answerScore": 45,
      "passScore": 686,
      "passTarget": 16,
      "rewardScore": 45,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 686
    },
    {
      "id": 36,
      "level": 36,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1501,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2150,
      "probability": {
        "normal": 50,
        "helmet": 71,
        "bomb": 83,
        "white": 94,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 244,
      "answerScore": 46,
      "passScore": 702,
      "passTarget": 16,
      "rewardScore": 46,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 702
    },
    {
      "id": 37,
      "level": 37,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1460,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2075,
      "probability": {
        "normal": 48,
        "helmet": 70,
        "bomb": 82,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 248,
      "answerScore": 47,
      "passScore": 733,
      "passTarget": 16,
      "rewardScore": 47,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 733
    },
    {
      "id": 38,
      "level": 38,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1420,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 2000,
      "probability": {
        "normal": 48,
        "helmet": 70,
        "bomb": 82,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 252,
      "answerScore": 48,
      "passScore": 764,
      "passTarget": 16,
      "rewardScore": 48,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 764
    },
    {
      "id": 39,
      "level": 39,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1379,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1925,
      "probability": {
        "normal": 48,
        "helmet": 70,
        "bomb": 82,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 256,
      "answerScore": 49,
      "passScore": 796,
      "passTarget": 17,
      "rewardScore": 49,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 796
    },
    {
      "id": 40,
      "level": 40,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1339,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1850,
      "probability": {
        "normal": 45,
        "helmet": 68,
        "bomb": 81,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 260,
      "answerScore": 50,
      "passScore": 827,
      "passTarget": 17,
      "rewardScore": 50,
      "rewardType": 1,
      "rewardNum": 2,
      "limit": 827
    },
    {
      "id": 41,
      "level": 41,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1298,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1775,
      "probability": {
        "normal": 45,
        "helmet": 68,
        "bomb": 81,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 264,
      "answerScore": 51,
      "passScore": 858,
      "passTarget": 17,
      "rewardScore": 51,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 858
    },
    {
      "id": 42,
      "level": 42,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1258,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1700,
      "probability": {
        "normal": 45,
        "helmet": 68,
        "bomb": 81,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 268,
      "answerScore": 52,
      "passScore": 889,
      "passTarget": 18,
      "rewardScore": 52,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 889
    },
    {
      "id": 43,
      "level": 43,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1217,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1625,
      "probability": {
        "normal": 45,
        "helmet": 68,
        "bomb": 81,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 272,
      "answerScore": 53,
      "passScore": 920,
      "passTarget": 18,
      "rewardScore": 53,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 920
    },
    {
      "id": 44,
      "level": 44,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1177,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1550,
      "probability": {
        "normal": 44,
        "helmet": 68,
        "bomb": 81,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 276,
      "answerScore": 54,
      "passScore": 952,
      "passTarget": 18,
      "rewardScore": 54,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 952
    },
    {
      "id": 45,
      "level": 45,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1136,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1475,
      "probability": {
        "normal": 44,
        "helmet": 68,
        "bomb": 81,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 280,
      "answerScore": 55,
      "passScore": 983,
      "passTarget": 18,
      "rewardScore": 55,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 983
    },
    {
      "id": 46,
      "level": 46,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1096,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1400,
      "probability": {
        "normal": 44,
        "helmet": 68,
        "bomb": 81,
        "white": 93,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 284,
      "answerScore": 56,
      "passScore": 1014,
      "passTarget": 19,
      "rewardScore": 56,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 1014
    },
    {
      "id": 47,
      "level": 47,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1055,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1325,
      "probability": {
        "normal": 40,
        "helmet": 65,
        "bomb": 79,
        "white": 92,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 288,
      "answerScore": 57,
      "passScore": 1045,
      "passTarget": 19,
      "rewardScore": 57,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 1045
    },
    {
      "id": 48,
      "level": 48,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 1015,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1250,
      "probability": {
        "normal": 40,
        "helmet": 65,
        "bomb": 79,
        "white": 92,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 292,
      "answerScore": 58,
      "passScore": 1076,
      "passTarget": 19,
      "rewardScore": 58,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 1076
    },
    {
      "id": 49,
      "level": 49,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 974,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1175,
      "probability": {
        "normal": 40,
        "helmet": 65,
        "bomb": 79,
        "white": 92,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 296,
      "answerScore": 59,
      "passScore": 1108,
      "passTarget": 19,
      "rewardScore": 59,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 1108
    },
    {
      "id": 50,
      "level": 50,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 934,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1100,
      "probability": {
        "normal": 39,
        "helmet": 65,
        "bomb": 79,
        "white": 92,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 300,
      "answerScore": 60,
      "passScore": 1170,
      "passTarget": 20,
      "rewardScore": 60,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 1170
    },
    {
      "id": 51,
      "level": 51,
      "num": "5*4",
      "cols": 5,
      "rows": 4,
      "lineCount": 2,
      "lineSpace": 934,
      "countMin": 1,
      "countMax": 3,
      "reactionMs": 1100,
      "probability": {
        "normal": 39,
        "helmet": 65,
        "bomb": 79,
        "white": 92,
        "other": 100
      },
      "fault": 3,
      "roundSeconds": 30,
      "brains": 300,
      "answerScore": 60,
      "passScore": 1170,
      "passTarget": 20,
      "rewardScore": 60,
      "rewardType": 1,
      "rewardNum": 3,
      "limit": 1170
    }
  ],
  "rules": {
    "upgrade": "小关结束时满足通关目标，难度 +1。",
    "downgrade": "未达标：第 1 次失败保持原难度；第 2 次失败难度 -1；第 3 次失败难度 -3，并清空连续失败次数；最低为 1 级。",
    "roundEnd": "连续选错两次或小关倒计时 time=0。",
    "continueAfterPass": "达成目标后不提前终止训练，继续到下发训练时间结束，并回传 passFlag。",
    "scoreFormula": "通关时 floor(通关积分 + (实际数 - 目标数) * 奖励分 + 10)；未通关固定 10 分。",
    "targetLabel": "游戏界面显示目标数 N/M。",
    "autoContinue": "小关结束后非阻塞自动续训；训练总时长未归零时不提供结束训练入口。"
  },
  "autoContinueRoundMs": 900,
  "polishFeatures": [
    "target-progress-meter",
    "fault-warning-meter",
    "result-trend-dashboard",
    "tutorial-completion-state",
    "asset-preloading",
    "visibility-auto-pause",
    "pass-flash-timer-guard",
    "reduced-motion-support",
    "three-difficulty-preset-selector",
    "responsive-viewport-board-fit"
  ],
  "difficultyPresets": [
    {
      "id": "easy",
      "name": "容易",
      "startLevel": 1,
      "label": "容易",
      "description": "从第 1 关开始，适合首次训练或儿童热身。"
    },
    {
      "id": "normal",
      "name": "普通",
      "startLevel": 15,
      "label": "普通",
      "description": "从第 15 关开始，节奏与目标明显提高。"
    },
    {
      "id": "hard",
      "name": "困难",
      "startLevel": 30,
      "label": "困难",
      "description": "从第 30 关开始，目标高、反应时间短。"
    }
  ],
  "difficultyPresetRule": "容易从第 1 关开始；普通从第 15 关开始；困难从第 30 关开始。每次正式训练开始时按所选档位重置起始关卡，训练中仍按通过/失败规则升降级。"
};
