package com.a620.tablet.training

import java.security.MessageDigest
import java.security.SecureRandom

/**
 * Defense-in-depth channel authentication inside the same application UID.
 *
 * The raw token is generated by the controller for every binding and is never
 * persisted. The training service authenticates calls by comparing SHA-256
 * digests in constant time. A new token starts a new channel epoch, so a main
 * process restart may safely restart its local generation counter at one while
 * any delayed calls from the old binding remain invalid.
 */
object ChannelAuthenticator {
    private val tokenRegex = Regex("^[0-9a-f]{${RuntimePolicy.CHANNEL_TOKEN_CHARS}}$")
    private val random = SecureRandom()

    fun generateToken(): String {
        val bytes = ByteArray(RuntimePolicy.CHANNEL_TOKEN_BYTES)
        random.nextBytes(bytes)
        return bytes.joinToString("") { "%02x".format(it) }
    }

    fun requireValidToken(token: String) {
        require(tokenRegex.matches(token)) { "invalid channel token syntax" }
    }

    fun digest(token: String): ByteArray {
        requireValidToken(token)
        return MessageDigest.getInstance("SHA-256").digest(token.toByteArray(Charsets.US_ASCII))
    }

    fun constantTimeSameToken(left: String?, right: String?): Boolean {
        if (left == null || right == null) return false
        return try { MessageDigest.isEqual(digest(left), digest(right)) } catch (_: IllegalArgumentException) { false }
    }

    fun matches(token: String, expectedDigest: ByteArray?): Boolean {
        if (expectedDigest == null || !tokenRegex.matches(token)) return false
        return MessageDigest.isEqual(digest(token), expectedDigest)
    }
}
