// generated; do not edit
package com.a620.tablet.training

object RuntimePolicy {
    const val PROFILE = "A620-ARS-1"
    const val CONTRACT_VERSION = "A620-TRC-1.1"
    const val PROFILE_SHA256 = "6e994f0150cfae49ce5a5ad3480d1d2453febf6288ce2a07c1300479a81254fc"
    const val INLINE_CANONICAL_MAX_BYTES = 49152
    const val BULK_CANONICAL_MAX_BYTES = 2097152
    const val ACTOR_QUEUE_MAX_MESSAGES = 96
    const val ACTOR_QUEUE_MAX_BYTES = 5242880
    const val URGENT_QUEUE_MAX_MESSAGES = 32
    const val URGENT_QUEUE_MAX_BYTES = 4194304
    const val NORMAL_QUEUE_MAX_MESSAGES = 64
    const val NORMAL_QUEUE_MAX_BYTES = 1048576
    const val PRESERVE_INGRESS_ORDER_ACROSS_RESERVED_LANES = true
    const val BULK_IO_WORKERS = 2
    const val BULK_IO_QUEUE_MAX_MESSAGES = 4
    const val MAX_INFLIGHT_BULK_MESSAGES = 4
    const val MAX_INFLIGHT_BULK_BYTES = 4194304
    const val BULK_READ_TIMEOUT_MS = 15000L
    val URGENT_MESSAGE_TYPES: Set<String> = setOf("TERMINATE","DEADLINE","PAUSE","ACK_RESULT_COMMITTED","READY","STARTED","BATCH_CLOSED","PAUSED","RESUMED","RESULT_READY","TERMINATED","COMMAND_ACCEPTED","COMMAND_REJECTED","RUNTIME_ERROR")
    val DROPPABLE_ON_BACKPRESSURE_MESSAGE_TYPES: Set<String> = setOf("HEARTBEAT","STATE_SNAPSHOT")
    const val MAX_POINTERS = 10
    const val CANCEL_ACTIVE_STREAM_ON_BOUNDARY = true
    const val FORWARD_PLATFORM_CANCEL = true
    const val CALLBACK_REGISTRATION_TIMEOUT_MS = 5000L
    const val CHANNEL_AUTH_PROFILE = "A620-ACS-1"
    const val CHANNEL_TOKEN_BYTES = 32
    const val CHANNEL_TOKEN_CHARS = 64
    const val CHANNEL_TOKEN_PERSISTS_RAW = false
    const val CHANNEL_TOKEN_RETAIN_RAW_IN_MEMORY_FOR_CALLBACKS = true
    const val CHANNEL_TOKEN_CONSTANT_TIME_COMPARE = true
    const val RECEIVER_CLOSES_INBOUND_PFD_AFTER_DUP = true
    const val EXPOSE_RAW_AIDL_INTERFACE = false
}
